# Site settings
title: francescodelduchetto lecture's notes
email: francescodelduchetto@gmail.com
description: "This website contains my lecture's notes (oh what a surprise!) while I'm attending the master course in ''Artificial Intelligence and Robotics'' at Sapienza University (Rome). I'm doing this only as an incentive to review the contents of the lectures just after each class. So, it could happens that I stop at any time, because I'll become bored of this or because I'll decide to cram for my exams!"
baseurl: ""
url: ""
twitter_username: fratreno
github_username:  francescodelduchetto

# Build settings
markdown: kramdown
permalink: pretty
