# Site settings
title: My lecture notes
email: francescodelduchetto@gmail.com
description: "Here I write the notes of the lectures I'm attending during the master course in 'Artificial Intelligence and Robotics' at Sapienza University (Rome)."
#~ baseurl: "/lectureNotes"
url: ""
github_username:  francescodelduchetto

# Build settings
markdown: kramdown
permalink: pretty

# Sitemap
gems:
  - jekyll-sitemap
